# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dasom Ahn
tagline:          ':)'
description:      ''
url:              https://tommy-ahn.github.io/
baseurl:          /

author:
  name:           'Dasom Ahn'
  url:            https://tommy-ahn.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           -
